export const componentsContent = [
  {
    id: "root",
    type: "html",
    indent: 0,
    classNameValues: ["root"],
    parentId: null,
    value: "div",
  },
  {
    id: "header",
    type: "component",
    indent: 1,
    classNameValues: [],
    parentId: "root",
    value: "Header",
  },
  {
    id: "pageTitle",
    type: "html",
    indent: 2,
    classNameValues: ["headingLarge", "pageTitle"],
    parentId: "header",
    value: "h1",
  },
  {
    id: "title",
    type: "text",
    indent: 3,
    classNameValues: [],
    parentId: "pageTitle",
    value: "Daily Habit Tracker",
  },
  {
    id: "habitList",
    type: "component",
    indent: 1,
    classNameValues: ["habitList"],
    selected: true,
    parentId: "root",
    value: "HabitList",
  },
  {
    id: "habitItem_expression",
    type: "expression",
    indent: 2,
    classNameValues: [],
    parentId: "habitList",
    value: "habits.map(habit => ( ... ))",
  },
  {
    id: "habitItem",
    type: "component",
    indent: 3,
    classNameValues: ["item"],
    parentId: "habitItem_expression",
    value: "HabitItem",
  },
  {
    id: "habitTitle",
    type: "html",
    indent: 4,
    classNameValues: ["habitTitle"],
    parentId: "habitItem",
    value: "h3",
  },
  {
    id: "habitName",
    type: "expression",
    indent: 5,
    classNameValues: [],
    parentId: "habitTitle",
    value: "habit.name",
  },
  {
    id: "habitCheckbox",
    type: "component",
    indent: 4,
    classNameValues: ["status"],
    parentId: "habitItem",
    value: "Checkbox",
  },
  {
    id: "addHabitForm",
    type: "component",
    indent: 1,
    classNameValues: [],
    parentId: "root",
    value: "AddHabitForm",
  },
  {
    id: "inputField",
    type: "component",
    indent: 2,
    classNameValues: ["habitNameInput"],
    parentId: "addHabitForm",
    value: "InputField",
  },
  {
    id: "actions",
    type: "html",
    indent: 2,
    classNameValues: ["actions"],
    parentId: "addHabitForm",
    value: "div",
  },
  {
    id: "addButton",
    type: "component",
    indent: 3,
    classNameValues: [],
    parentId: "addHabitForm",
    value: "Button",
  },
  {
    id: "addButtonTitle",
    type: "text",
    indent: 4,
    classNameValues: [],
    parentId: "addButton",
    value: "Add Habit",
  },
  {
    id: "cancelButton",
    type: "component",
    indent: 3,
    classNameValues: [],
    parentId: "addHabitForm",
    value: "Button",
  },
  {
    id: "cancelButtonTitle",
    type: "text",
    indent: 4,
    classNameValues: [],
    parentId: "cancelButton",
    value: "Cancel",
  },
  {
    id: "footer",
    type: "component",
    indent: 1,
    classNameValues: [],
    parentId: "root",
    value: "Footer",
  },
];
